/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.haui_megatech.view;

import com.haui_megatech.theme.GlobalColor;
import java.awt.Color;

/**
 *
 * @author vieth
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        welcomeMessage = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        productTab = new javax.swing.JPanel();
        productLabel = new javax.swing.JLabel();
        providerTab = new javax.swing.JPanel();
        providerLabel = new javax.swing.JLabel();
        importProductTab = new javax.swing.JPanel();
        importProductLabel = new javax.swing.JLabel();
        importBillTab = new javax.swing.JPanel();
        importBillLabel = new javax.swing.JLabel();
        exportProductTab = new javax.swing.JPanel();
        exportProductLabel = new javax.swing.JLabel();
        exportBillTab = new javax.swing.JPanel();
        exportBillLabel = new javax.swing.JLabel();
        inStockTab = new javax.swing.JPanel();
        inStockLabel = new javax.swing.JLabel();
        userTab = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        statisticsTab = new javax.swing.JPanel();
        statisticsLabel = new javax.swing.JLabel();
        updateInfoTab = new javax.swing.JPanel();
        updateInfoLabel = new javax.swing.JLabel();
        logoutTab = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        providerPanel = new javax.swing.JPanel();
        importProductPanel = new javax.swing.JPanel();
        importBillPanel = new javax.swing.JPanel();
        exportProductPanel = new javax.swing.JPanel();
        exportBillPanel = new javax.swing.JPanel();
        inStockPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        statisticPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(51, 153, 255));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(256, 800));

        welcomeMessage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMessage.setText("Chào mừng");

        username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 0));
        username.setText("Admin");

        productTab.setBackground(new java.awt.Color(255, 255, 255));
        productTab.setPreferredSize(new java.awt.Dimension(240, 40));
        productTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTabMouseClicked(evt);
            }
        });

        productLabel.setBackground(new java.awt.Color(255, 255, 255));
        productLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productLabel.setText("SẢN PHẨM");
        productLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productTabLayout = new javax.swing.GroupLayout(productTab);
        productTab.setLayout(productTabLayout);
        productTabLayout.setHorizontalGroup(
            productTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTabLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(productLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productTabLayout.setVerticalGroup(
            productTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productTabLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(productLabel)
                .addContainerGap())
        );

        providerTab.setBackground(new java.awt.Color(255, 255, 255));
        providerTab.setPreferredSize(new java.awt.Dimension(240, 40));
        providerTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                providerTabMouseClicked(evt);
            }
        });

        providerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        providerLabel.setText("NHÀ CUNG CẤP");
        providerLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        providerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                providerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout providerTabLayout = new javax.swing.GroupLayout(providerTab);
        providerTab.setLayout(providerTabLayout);
        providerTabLayout.setHorizontalGroup(
            providerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, providerTabLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(providerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        providerTabLayout.setVerticalGroup(
            providerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(providerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(providerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        importProductTab.setBackground(new java.awt.Color(255, 255, 255));
        importProductTab.setPreferredSize(new java.awt.Dimension(240, 40));
        importProductTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importProductTabMouseClicked(evt);
            }
        });

        importProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importProductLabel.setText("NHẬP HÀNG");
        importProductLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        importProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importProductLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout importProductTabLayout = new javax.swing.GroupLayout(importProductTab);
        importProductTab.setLayout(importProductTabLayout);
        importProductTabLayout.setHorizontalGroup(
            importProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importProductTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(importProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        importProductTabLayout.setVerticalGroup(
            importProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importProductTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        importBillTab.setBackground(new java.awt.Color(255, 255, 255));
        importBillTab.setPreferredSize(new java.awt.Dimension(240, 40));
        importBillTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importBillTabMouseClicked(evt);
            }
        });

        importBillLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importBillLabel.setText("PHIẾU NHẬP");
        importBillLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        importBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importBillLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout importBillTabLayout = new javax.swing.GroupLayout(importBillTab);
        importBillTab.setLayout(importBillTabLayout);
        importBillTabLayout.setHorizontalGroup(
            importBillTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importBillTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(importBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        importBillTabLayout.setVerticalGroup(
            importBillTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importBillTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exportProductTab.setBackground(new java.awt.Color(255, 255, 255));
        exportProductTab.setPreferredSize(new java.awt.Dimension(240, 40));
        exportProductTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportProductTabMouseClicked(evt);
            }
        });

        exportProductLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exportProductLabel.setText("XUẤT HÀNG");
        exportProductLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        exportProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportProductLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exportProductTabLayout = new javax.swing.GroupLayout(exportProductTab);
        exportProductTab.setLayout(exportProductTabLayout);
        exportProductTabLayout.setHorizontalGroup(
            exportProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exportProductTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        exportProductTabLayout.setVerticalGroup(
            exportProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportProductTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exportBillTab.setBackground(new java.awt.Color(255, 255, 255));
        exportBillTab.setPreferredSize(new java.awt.Dimension(240, 40));
        exportBillTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportBillTabMouseClicked(evt);
            }
        });

        exportBillLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exportBillLabel.setText("PHIẾU XUẤT");
        exportBillLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        exportBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportBillLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exportBillTabLayout = new javax.swing.GroupLayout(exportBillTab);
        exportBillTab.setLayout(exportBillTabLayout);
        exportBillTabLayout.setHorizontalGroup(
            exportBillTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exportBillTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        exportBillTabLayout.setVerticalGroup(
            exportBillTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportBillTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inStockTab.setBackground(new java.awt.Color(255, 255, 255));
        inStockTab.setPreferredSize(new java.awt.Dimension(240, 40));
        inStockTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inStockTabMouseClicked(evt);
            }
        });

        inStockLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inStockLabel.setText("TỒN KHO");
        inStockLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        inStockLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inStockLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout inStockTabLayout = new javax.swing.GroupLayout(inStockTab);
        inStockTab.setLayout(inStockTabLayout);
        inStockTabLayout.setHorizontalGroup(
            inStockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inStockTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        inStockTabLayout.setVerticalGroup(
            inStockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inStockTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userTab.setBackground(new java.awt.Color(255, 255, 255));
        userTab.setPreferredSize(new java.awt.Dimension(240, 40));
        userTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTabMouseClicked(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userLabel.setText("TÀI KHOẢN");
        userLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userTabLayout = new javax.swing.GroupLayout(userTab);
        userTab.setLayout(userTabLayout);
        userTabLayout.setHorizontalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        userTabLayout.setVerticalGroup(
            userTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statisticsTab.setBackground(new java.awt.Color(255, 255, 255));
        statisticsTab.setPreferredSize(new java.awt.Dimension(240, 40));
        statisticsTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsTabMouseClicked(evt);
            }
        });

        statisticsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        statisticsLabel.setText("THỐNG KÊ");
        statisticsLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        statisticsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout statisticsTabLayout = new javax.swing.GroupLayout(statisticsTab);
        statisticsTab.setLayout(statisticsTabLayout);
        statisticsTabLayout.setHorizontalGroup(
            statisticsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticsTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statisticsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        statisticsTabLayout.setVerticalGroup(
            statisticsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statisticsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateInfoTab.setBackground(new java.awt.Color(255, 255, 255));
        updateInfoTab.setPreferredSize(new java.awt.Dimension(240, 40));
        updateInfoTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateInfoTabMouseClicked(evt);
            }
        });

        updateInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateInfoLabel.setText("ĐỔI THÔNG TIN");
        updateInfoLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        updateInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateInfoLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout updateInfoTabLayout = new javax.swing.GroupLayout(updateInfoTab);
        updateInfoTab.setLayout(updateInfoTabLayout);
        updateInfoTabLayout.setHorizontalGroup(
            updateInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateInfoTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        updateInfoTabLayout.setVerticalGroup(
            updateInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInfoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoutTab.setBackground(new java.awt.Color(255, 255, 255));
        logoutTab.setPreferredSize(new java.awt.Dimension(240, 40));
        logoutTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutTabMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutLabel.setText("ĐĂNG XUẤT");
        logoutLabel.setPreferredSize(new java.awt.Dimension(240, 40));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutTabLayout = new javax.swing.GroupLayout(logoutTab);
        logoutTab.setLayout(logoutTabLayout);
        logoutTabLayout.setHorizontalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        logoutTabLayout.setVerticalGroup(
            logoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productTab, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(providerTab, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(importProductTab, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(importBillTab, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(exportProductTab, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(exportBillTab, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(inStockTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeMessage)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(username)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(userTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(statisticsTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(updateInfoTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(logoutTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(welcomeMessage)
                .addGap(18, 18, 18)
                .addComponent(username)
                .addGap(94, 94, 94)
                .addComponent(productTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(providerTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importProductTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importBillTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportProductTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportBillTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inStockTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statisticsTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 840));

        productPanel.setBackground(new java.awt.Color(204, 255, 255));
        productPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        jLabel1.setText("Product panel");

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel1)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        getContentPane().add(productPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        providerPanel.setBackground(new java.awt.Color(204, 204, 255));
        providerPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout providerPanelLayout = new javax.swing.GroupLayout(providerPanel);
        providerPanel.setLayout(providerPanelLayout);
        providerPanelLayout.setHorizontalGroup(
            providerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        providerPanelLayout.setVerticalGroup(
            providerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(providerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        importProductPanel.setBackground(new java.awt.Color(204, 255, 51));
        importProductPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout importProductPanelLayout = new javax.swing.GroupLayout(importProductPanel);
        importProductPanel.setLayout(importProductPanelLayout);
        importProductPanelLayout.setHorizontalGroup(
            importProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        importProductPanelLayout.setVerticalGroup(
            importProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(importProductPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        importBillPanel.setBackground(new java.awt.Color(0, 255, 255));
        importBillPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout importBillPanelLayout = new javax.swing.GroupLayout(importBillPanel);
        importBillPanel.setLayout(importBillPanelLayout);
        importBillPanelLayout.setHorizontalGroup(
            importBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        importBillPanelLayout.setVerticalGroup(
            importBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(importBillPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        exportProductPanel.setBackground(new java.awt.Color(204, 255, 255));
        exportProductPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout exportProductPanelLayout = new javax.swing.GroupLayout(exportProductPanel);
        exportProductPanel.setLayout(exportProductPanelLayout);
        exportProductPanelLayout.setHorizontalGroup(
            exportProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        exportProductPanelLayout.setVerticalGroup(
            exportProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(exportProductPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        exportBillPanel.setBackground(new java.awt.Color(204, 255, 255));
        exportBillPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout exportBillPanelLayout = new javax.swing.GroupLayout(exportBillPanel);
        exportBillPanel.setLayout(exportBillPanelLayout);
        exportBillPanelLayout.setHorizontalGroup(
            exportBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        exportBillPanelLayout.setVerticalGroup(
            exportBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(exportBillPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        inStockPanel.setBackground(new java.awt.Color(204, 255, 255));
        inStockPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout inStockPanelLayout = new javax.swing.GroupLayout(inStockPanel);
        inStockPanel.setLayout(inStockPanelLayout);
        inStockPanelLayout.setHorizontalGroup(
            inStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        inStockPanelLayout.setVerticalGroup(
            inStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(inStockPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        userPanel.setBackground(new java.awt.Color(204, 255, 255));
        userPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        statisticPanel.setBackground(new java.awt.Color(204, 255, 255));
        statisticPanel.setPreferredSize(new java.awt.Dimension(720, 640));

        javax.swing.GroupLayout statisticPanelLayout = new javax.swing.GroupLayout(statisticPanel);
        statisticPanel.setLayout(statisticPanelLayout);
        statisticPanelLayout.setHorizontalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        statisticPanelLayout.setVerticalGroup(
            statisticPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(statisticPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1040, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setActiveTab(String tabName) {
        switch (tabName) {
            case "product" -> {
                this.productTab.setBackground(Color.YELLOW);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "provider" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.YELLOW);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "import-product" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.YELLOW);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "import-bill" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.YELLOW);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "export-product" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.YELLOW);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "export-bill" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.YELLOW);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "in-stock" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.YELLOW);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "user" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.YELLOW);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
            case "statistics" -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.YELLOW);
                break;
            }

            default -> {
                this.productTab.setBackground(Color.WHITE);
                this.providerTab.setBackground(Color.WHITE);
                this.importProductTab.setBackground(Color.WHITE);
                this.importBillTab.setBackground(Color.WHITE);
                this.exportProductTab.setBackground(Color.WHITE);
                this.exportBillTab.setBackground(Color.WHITE);
                this.inStockTab.setBackground(Color.WHITE);
                this.userTab.setBackground(Color.WHITE);
                this.statisticsTab.setBackground(Color.WHITE);
                break;
            }
        }
    }

    private void productLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Product label");
        this.setActiveTab("product");

    }//GEN-LAST:event_productLabelMouseClicked

    private void providerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providerLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Provider label");
        this.setActiveTab("provider");
    }//GEN-LAST:event_providerLabelMouseClicked

    private void importProductLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importProductLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Import Product label");
        this.setActiveTab("import-product");
    }//GEN-LAST:event_importProductLabelMouseClicked

    private void importBillLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importBillLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Import Bill label");
        this.setActiveTab("import-bill");
    }//GEN-LAST:event_importBillLabelMouseClicked

    private void exportProductLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportProductLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Export Product label");
        this.setActiveTab("export-product");
    }//GEN-LAST:event_exportProductLabelMouseClicked

    private void statisticsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Statistic label");
        this.setActiveTab("statistics");
    }//GEN-LAST:event_statisticsLabelMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside User label");
        this.setActiveTab("user");
    }//GEN-LAST:event_userLabelMouseClicked

    private void updateInfoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateInfoLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Update Info label");
        this.setActiveTab("");
    }//GEN-LAST:event_updateInfoLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Logout label");
        this.setActiveTab("");
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void productTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTabMouseClicked
        // TODO add your handling code here:
        this.productLabelMouseClicked(evt);
    }//GEN-LAST:event_productTabMouseClicked

    private void providerTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providerTabMouseClicked
        // TODO add your handling code here:
        this.providerLabelMouseClicked(evt);
    }//GEN-LAST:event_providerTabMouseClicked

    private void importProductTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importProductTabMouseClicked
        // TODO add your handling code here:
        this.importProductLabelMouseClicked(evt);
    }//GEN-LAST:event_importProductTabMouseClicked

    private void importBillTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importBillTabMouseClicked
        // TODO add your handling code here:
        this.importBillLabelMouseClicked(evt);
    }//GEN-LAST:event_importBillTabMouseClicked

    private void exportProductTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportProductTabMouseClicked
        // TODO add your handling code here:
        this.exportProductLabelMouseClicked(evt);
    }//GEN-LAST:event_exportProductTabMouseClicked

    private void exportBillTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportBillTabMouseClicked
        // TODO add your handling code here:
        this.exportBillLabelMouseClicked(evt);
    }//GEN-LAST:event_exportBillTabMouseClicked

    private void exportBillLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportBillLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside Export Bill label");
        this.setActiveTab("export-bill");

    }//GEN-LAST:event_exportBillLabelMouseClicked

    private void inStockLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inStockLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Inside In Stock label");
        this.setActiveTab("in-stock");

    }//GEN-LAST:event_inStockLabelMouseClicked

    private void inStockTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inStockTabMouseClicked
        // TODO add your handling code here:
        this.inStockLabelMouseClicked(evt);
    }//GEN-LAST:event_inStockTabMouseClicked

    private void userTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTabMouseClicked
        // TODO add your handling code here:
        this.userLabelMouseClicked(evt);
    }//GEN-LAST:event_userTabMouseClicked

    private void statisticsTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsTabMouseClicked
        // TODO add your handling code here:
        this.statisticsLabelMouseClicked(evt);
    }//GEN-LAST:event_statisticsTabMouseClicked

    private void updateInfoTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateInfoTabMouseClicked
        // TODO add your handling code here:
        this.updateInfoLabelMouseClicked(evt);
    }//GEN-LAST:event_updateInfoTabMouseClicked

    private void logoutTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutTabMouseClicked
        // TODO add your handling code here:
        this.logoutLabelMouseClicked(evt);
    }//GEN-LAST:event_logoutTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exportBillLabel;
    private javax.swing.JPanel exportBillPanel;
    private javax.swing.JPanel exportBillTab;
    private javax.swing.JLabel exportProductLabel;
    private javax.swing.JPanel exportProductPanel;
    private javax.swing.JPanel exportProductTab;
    private javax.swing.JLabel importBillLabel;
    private javax.swing.JPanel importBillPanel;
    private javax.swing.JPanel importBillTab;
    private javax.swing.JLabel importProductLabel;
    private javax.swing.JPanel importProductPanel;
    private javax.swing.JPanel importProductTab;
    private javax.swing.JLabel inStockLabel;
    private javax.swing.JPanel inStockPanel;
    private javax.swing.JPanel inStockTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutTab;
    private javax.swing.JLabel productLabel;
    private javax.swing.JPanel productPanel;
    private javax.swing.JPanel productTab;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JPanel providerPanel;
    private javax.swing.JPanel providerTab;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel statisticPanel;
    private javax.swing.JLabel statisticsLabel;
    private javax.swing.JPanel statisticsTab;
    private javax.swing.JLabel updateInfoLabel;
    private javax.swing.JPanel updateInfoTab;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel userTab;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
