/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.haui_megatech.view;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author caoth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login_
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recoveryPasswordDiaglog = new javax.swing.JDialog();
        sendResetEmailPanel = new javax.swing.JPanel();
        sendRestEmailButton = new javax.swing.JButton();
        sendResetEmailLabel = new javax.swing.JLabel();
        sendResetCodePanel = new javax.swing.JPanel();
        sendResetCodeButton = new javax.swing.JButton();
        sendResetCodeLabel = new javax.swing.JLabel();
        updateNewPasswordPanel = new javax.swing.JPanel();
        updateNewPasswordButton = new javax.swing.JButton();
        updateNewPasswordLabel = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        dangNhapTittle = new javax.swing.JLabel();
        tendnlabel = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        passlabel = new javax.swing.JLabel();
        uPass = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        forget = new javax.swing.JLabel();

        recoveryPasswordDiaglog.setMinimumSize(new java.awt.Dimension(400, 300));

        sendResetEmailPanel.setMinimumSize(new java.awt.Dimension(400, 300));

        sendRestEmailButton.setText("Gửi mã xác nhận");
        sendRestEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRestEmailButtonActionPerformed(evt);
            }
        });

        sendResetEmailLabel.setText("Nhập địa chỉ email");

        javax.swing.GroupLayout sendResetEmailPanelLayout = new javax.swing.GroupLayout(sendResetEmailPanel);
        sendResetEmailPanel.setLayout(sendResetEmailPanelLayout);
        sendResetEmailPanelLayout.setHorizontalGroup(
            sendResetEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendResetEmailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendRestEmailButton)
                .addGap(37, 37, 37))
            .addGroup(sendResetEmailPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(sendResetEmailLabel)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        sendResetEmailPanelLayout.setVerticalGroup(
            sendResetEmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendResetEmailPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(sendResetEmailLabel)
                .addGap(49, 49, 49)
                .addComponent(sendRestEmailButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        sendResetCodeButton.setText("Xác nhận");
        sendResetCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendResetCodeButtonActionPerformed(evt);
            }
        });

        sendResetCodeLabel.setText("Nhập mã xác nhận");

        javax.swing.GroupLayout sendResetCodePanelLayout = new javax.swing.GroupLayout(sendResetCodePanel);
        sendResetCodePanel.setLayout(sendResetCodePanelLayout);
        sendResetCodePanelLayout.setHorizontalGroup(
            sendResetCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendResetCodePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendResetCodeButton)
                .addGap(37, 37, 37))
            .addGroup(sendResetCodePanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(sendResetCodeLabel)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        sendResetCodePanelLayout.setVerticalGroup(
            sendResetCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendResetCodePanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(sendResetCodeLabel)
                .addGap(49, 49, 49)
                .addComponent(sendResetCodeButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        updateNewPasswordButton.setText("Cập nhật mật khẩu");
        updateNewPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNewPasswordButtonActionPerformed(evt);
            }
        });

        updateNewPasswordLabel.setText("Nhập mật khẩu mới");

        javax.swing.GroupLayout updateNewPasswordPanelLayout = new javax.swing.GroupLayout(updateNewPasswordPanel);
        updateNewPasswordPanel.setLayout(updateNewPasswordPanelLayout);
        updateNewPasswordPanelLayout.setHorizontalGroup(
            updateNewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateNewPasswordPanelLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(updateNewPasswordButton)
                .addGap(37, 37, 37))
            .addGroup(updateNewPasswordPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(updateNewPasswordLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateNewPasswordPanelLayout.setVerticalGroup(
            updateNewPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateNewPasswordPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(updateNewPasswordLabel)
                .addGap(63, 63, 63)
                .addComponent(updateNewPasswordButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout recoveryPasswordDiaglogLayout = new javax.swing.GroupLayout(recoveryPasswordDiaglog.getContentPane());
        recoveryPasswordDiaglog.getContentPane().setLayout(recoveryPasswordDiaglogLayout);
        recoveryPasswordDiaglogLayout.setHorizontalGroup(
            recoveryPasswordDiaglogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sendResetCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(recoveryPasswordDiaglogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recoveryPasswordDiaglogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(updateNewPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
            .addGroup(recoveryPasswordDiaglogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recoveryPasswordDiaglogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sendResetEmailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        recoveryPasswordDiaglogLayout.setVerticalGroup(
            recoveryPasswordDiaglogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sendResetCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(recoveryPasswordDiaglogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recoveryPasswordDiaglogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(updateNewPasswordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
            .addGroup(recoveryPasswordDiaglogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recoveryPasswordDiaglogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sendResetEmailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setSize(new java.awt.Dimension(1384, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(44, 43, 196));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 692, 750));

        right.setBackground(new java.awt.Color(255, 255, 255));

        dangNhapTittle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dangNhapTittle.setForeground(new java.awt.Color(44, 43, 196));
        dangNhapTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dangNhapTittle.setText("ĐĂNG NHẬP");

        tendnlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tendnlabel.setText("Tên đăng nhập");

        uName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        passlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passlabel.setText("Mật khẩu");

        uPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        loginBtn.setBackground(new java.awt.Color(44, 43, 196));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Đăng nhập");

        forget.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        forget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forget.setText("Quên mật khẩu?");
        forget.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addComponent(dangNhapTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(forget, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(tendnlabel)
                    .addComponent(passlabel)
                    .addComponent(uName)
                    .addComponent(uPass)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(dangNhapTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(tendnlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(passlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uPass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forget)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 0, 692, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked
        // TODO add your handling code here:
        this.recoveryPasswordDiaglog.setVisible(true);
        this.recoveryPasswordDiaglog.setLocationRelativeTo(this);

        this.sendResetCodePanel.setVisible(false);
        this.sendResetEmailPanel.setVisible(true);
        this.updateNewPasswordPanel.setVisible(false);

    }//GEN-LAST:event_forgetMouseClicked

    private void sendResetCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendResetCodeButtonActionPerformed
        // TODO add your handling code here:
        this.sendResetCodePanel.setVisible(false);
        this.sendResetEmailPanel.setVisible(false);
        this.updateNewPasswordPanel.setVisible(true);
    }//GEN-LAST:event_sendResetCodeButtonActionPerformed

    private void updateNewPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNewPasswordButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_updateNewPasswordButtonActionPerformed

    private void sendRestEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRestEmailButtonActionPerformed
        // TODO add your handling code here:
        this.sendResetCodePanel.setVisible(true);
        this.sendResetEmailPanel.setVisible(false);
        this.updateNewPasswordPanel.setVisible(false);
    }//GEN-LAST:event_sendRestEmailButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
                new Login().setVisible(true);
            });
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dangNhapTittle;
    private javax.swing.JLabel forget;
    private javax.swing.JPanel left;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passlabel;
    private javax.swing.JDialog recoveryPasswordDiaglog;
    private javax.swing.JPanel right;
    private javax.swing.JButton sendResetCodeButton;
    private javax.swing.JLabel sendResetCodeLabel;
    private javax.swing.JPanel sendResetCodePanel;
    private javax.swing.JLabel sendResetEmailLabel;
    private javax.swing.JPanel sendResetEmailPanel;
    private javax.swing.JButton sendRestEmailButton;
    private javax.swing.JLabel tendnlabel;
    private javax.swing.JTextField uName;
    private javax.swing.JPasswordField uPass;
    private javax.swing.JButton updateNewPasswordButton;
    private javax.swing.JLabel updateNewPasswordLabel;
    private javax.swing.JPanel updateNewPasswordPanel;
    // End of variables declaration//GEN-END:variables
}
